apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-api
  labels:
    app: sample-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-api
  template:
    metadata:
      labels:
        app: sample-app-api
    spec:
      containers:
      - name: sample-app-api
        image: sample-app-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
