apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-for-sample-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/koshitake2m2/playground_infra.git
    targetRevision: HEAD
    path: argocd/sample-app-config/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
